import fs from 'node:fs';
const change=(path,before,after)=>{const source=fs.readFileSync(path,'utf8');if(source.split(before).length!==2)throw Error('Nonunique repair anchor: '+path+' '+before);fs.writeFileSync(path,source.replace(before,after));};
change('src/desktop/renderer/ui.tsx','{render(item,start+i)}</div>)}</div>;}','{render(item,start+i)}</div>)}</div></div>;}');
change('src/desktop/renderer/index.tsx','notify(String(error));}}><textarea','notify(String(error));}}}><textarea');
change('src/desktop/renderer/index.tsx','useRef<ReturnType<typeof setTimeout>>()','useRef<ReturnType<typeof setTimeout>|undefined>(undefined)');
change('src/desktop/renderer/index.tsx','Empty,VirtualList,label','Empty,label');
change('src/desktop/renderer/work.tsx','label,Detail,jsonResult','label,jsonResult');
change('src/desktop/renderer/integrations.tsx','Row,splitLines,options','Row,splitLines');
change('src/desktop/renderer/trials.tsx','Row,Modal,Status,options','Row,Modal,options');
console.log('Repaired the two JSX delimiters and removed unused imports; no behavior or assertions weakened.');
