export const frontendHtml = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reserve / Perfect Harness Demo</title><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head>
<body><header><span class="brand">RESERVE<span class="dot">.</span></span><span class="label">A PERFECT HARNESS DEMO</span></header>
<main><section class="intro"><p class="eyebrow">YOUR TIME, WELL SPENT</p><h1>A little space<br>in your day.</h1><p class="description">Choose an available time. We will take care of saving your spot.</p><div class="detail">Live availability · Secure reservation</div></section>
<section class="panel"><p class="eyebrow">BOOK YOUR VISIT</p><h2>Find your moment</h2><form id="booking"><label for="slot">Available time</label><select id="slot" name="slot" required><option value="">Loading available times…</option></select><label for="name">Your name</label><input id="name" name="name" autocomplete="name" minlength="2" maxlength="80" placeholder="Alex Morgan" required><button type="submit" id="reserve">Reserve this time <span aria-hidden="true">↗</span></button><p id="status" role="status" aria-live="polite"></p></form><p class="fine-print">One reservation per time slot. No double bookings.</p></section></main>
<footer>Built and verified in an isolated workspace. Demo only; no production authentication.</footer></body></html>`;
export function frontendCss(broken: boolean): string {
  return `*{box-sizing:border-box}body{margin:0;background:#f3f3ed;color:#172b24;font-family:Arial,Helvetica,sans-serif}header{display:flex;align-items:center;justify-content:space-between;padding:30px 6vw;border-bottom:1px solid #d4dbd4}.brand{font-size:24px;font-weight:800;letter-spacing:-1px}.dot{color:#167852}.label,.eyebrow{font-size:11px;font-weight:700;letter-spacing:2px}main{${broken ? "width:1200px;" : "width:min(1120px,100%);"}margin:0 auto;padding:70px 6vw;display:grid;grid-template-columns:1.1fr 1fr;gap:60px;align-items:center}h1{font-size:clamp(42px,6vw,74px);line-height:1.02;letter-spacing:-3px;margin:22px 0}h2{font-size:28px;letter-spacing:-1px;margin:12px 0 28px}.description{font-size:17px;line-height:1.7;color:#51615a;max-width:340px}.detail{margin-top:36px;font-size:12px}.panel{background:white;border:1px solid #dce3da;border-radius:20px;padding:34px;box-shadow:0 16px 50px #173c2510}label{display:block;font-size:12px;font-weight:700;margin:18px 0 8px}input,select{font:inherit;width:100%;padding:14px;border:1px solid #cfdad3;border-radius:8px;background:#fbfcfa;color:#213b2d}button{display:flex;justify-content:space-between;width:100%;border:0;border-radius:8px;padding:16px;margin-top:26px;font:inherit;font-weight:700;color:white;background:#176846;cursor:pointer}button:disabled{opacity:.5;cursor:wait}input:focus,select:focus,button:focus-visible{outline:3px solid #9fcab0;outline-offset:2px}#status{font-size:14px;line-height:1.5;min-height:22px}.fine-print{font-size:11px;line-height:1.5;color:#6b776f;border-top:1px solid #ecf0e9;padding-top:18px;margin:8px 0 0}footer{padding:20px 6vw;font-size:11px;color:#69796d;border-top:1px solid #d4dbd4}@media(max-width:720px){header{padding:22px 6vw}.label{max-width:112px;text-align:right;font-size:9px}main{grid-template-columns:1fr;gap:30px;padding:36px 6vw}h1{font-size:48px}.description{font-size:15px}.detail{margin-top:20px}.panel{padding:25px}}`;
}
export const frontendJs = String.raw`
const form=document.querySelector('#booking'),select=document.querySelector('#slot'),status=document.querySelector('#status'),button=document.querySelector('#reserve');
async function load(){const response=await fetch('/api/slots');if(!response.ok)throw Error('Availability could not be loaded');const slots=await response.json();select.replaceChildren();for(const slot of slots.filter(s=>s.available)){const option=document.createElement('option');option.value=slot.id;option.textContent=slot.id;select.append(option);}button.disabled=!select.options.length;}
form.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;status.textContent='Saving your reservation…';try{const response=await fetch('/api/reservations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slot:select.value,name:document.querySelector('#name').value})});const data=await response.json();if(!response.ok)throw Error(data.error??'Reservation failed');status.textContent='Reservation confirmed for '+data.slot+'.';await load();}catch(error){status.textContent=error.message;}finally{button.disabled=!select.options.length;}});
load().catch(error=>{status.textContent=error.message;button.disabled=true;});
`;
