import{createTestRenderer}from'@opentui/core/testing';import{createRoot}from'@opentui/react';import{createElement}from'react';import{Resvg}from'@resvg/resvg-js';import{mkdir,writeFile}from'node:fs/promises';import{join,resolve}from'node:path';
import{App}from'../dist/ui/tui/app.js';import{DemoClient}from'../dist/ui/tui/demo.js';import{GuidedForm}from'../dist/ui/tui/form.js';import{skillWizard}from'../dist/ui/tui/skill-wizard.js';import{BindingForm}from'../dist/ui/tui/binding-form.js';import{SqliteStore}from'../dist/adapters/sqlite/store.js';import{StudioAdmin}from'../dist/skills/admin.js';import{defaultConfig}from'../dist/config/schema.js';import{control,selectManual,selectionClosure}from'../dist/skills/control.js';import{missingEditorChecks}from'../dist/validation/center.js';
const out=resolve(process.argv[2]??'test-results/v4-ui');await mkdir(out,{recursive:true});
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');const color=c=>{const b=c?.buffer;if(!b||b.length!==4)throw Error('Unknown native color encoding');return `rgba(${b[0]},${b[1]},${b[2]},${b[3]/255})`;};
const captures=[];
for(const name of['manual-empty','manual-selected','teams','profiles','modes','creator','model-form','evaluation-form','evaluations','validation'])for(const [cols,rows]of[[80,24],[140,40]]){
 const store=new SqliteStore(':memory:'),base=defaultConfig(),admin=new StudioAdmin(store,'/synthetic/state'),source='/synthetic/project',client=new DemoClient('running');let record=admin.registry.get(source,base),cfg=structuredClone(record.config);cfg.skills.mode='manual';cfg.skills.assignments.push({skillId:'perfect-postgres-backend',scope:'set',target:'frontend-web',decision:'disable'});admin.registry.update(source,base,record.hash,cfg);
 if(name==='manual-selected'){const r=store.list('skillReleases').find(s=>s.skillId==='perfect-postgres-backend');selectManual(store,source,base,r.id,r.hash,true,control(store,source).epoch,selectionClosure(store,source,r.id));}
 const snapshot=client.getSnapshot();snapshot.studio=admin.panel(source,base);snapshot.studio.validation={id:'demo-validation',at:'2026-09-14T00:00:00Z',build:{version:'0.4.0',sourceCommit:'DEMO',node:process.version,platform:process.platform,osRelease:'DEMO'},checks:missingEditorChecks(),inferenceRequests:0,note:'Fixture sintético de presentación. No comprobó cuentas ni editores personales.'};
 if(name==='evaluations')snapshot.studio.trials=[{trialId:'demo-comparison',releaseId:'demo-release',profileId:'backend',partition:'holdout',repetitions:1,status:'completed',specHash:'demo',mode:'mock-or-unexecuted',pairs:[{caseId:'caso-demo',repetition:0,verdict:'both-fail',qualityPassed:false,noRegression:true}],qualityPassed:false,complete:true,claims:'DEMO: ambos fallan NO significa calidad aprobada.',requests:4,tokens:2200,budget:{maxRequests:16,maxTokens:96000}}];
 const ui=await createTestRenderer({width:cols,height:rows,kittyKeyboard:true}),root=createRoot(ui.renderer);
 const mappings={'manual-empty':'skills','manual-selected':'skills',teams:'teams',profiles:'profiles',modes:'modes',evaluations:'skill-trials',validation:'local-validation'};
 let element;
 if(name==='creator')element=createElement(GuidedForm,{spec:skillWizard('create',snapshot,'',()=>{}),width:cols,height:rows,motion:'off',onCancel:()=>{}});
 else if(name==='model-form')element=createElement(BindingForm,{profile:snapshot.studio.config.profiles.find(p=>p.id==='backend'),width:cols,height:rows,motion:'off',onSave:()=>{},onCancel:()=>{}});
 else if(name==='evaluation-form')element=createElement(GuidedForm,{spec:skillWizard('evaluate-code',snapshot,snapshot.studio.skills.find(s=>s.id==='perfect-postgres-backend').releaseId,()=>{}),width:cols,height:rows,motion:'off',onCancel:()=>{}});
 else element=createElement(App,{client,initialScreen:mappings[name],onExit:()=>{}});
 try{
  root.render(element);await new Promise(r=>setTimeout(r,90));await ui.renderOnce();
  const frame=ui.captureCharFrame(),spans=ui.captureSpans(),cw=10,ch=20,pad=24,label=30,width=cols*cw+2*pad,height=rows*ch+2*pad+label;
  let svg=`<rect width="100%" height="100%" fill="#050507"/><text x="24" y="20" fill="#9ba6bc" font-family="DejaVu Sans Mono,monospace" font-size="11">Perfect V4 · OpenTUI real · presentación con datos DEMO · ${cols}×${rows}</text>`;
  for(const [r,line]of spans.lines.entries()){let c=0;for(const span of line.spans){const x=pad+c*cw,y=pad+label+r*ch;svg+=`<rect x="${x}" y="${y}" width="${span.width*cw}" height="${ch}" fill="${color(span.bg)}"/><text xml:space="preserve" x="${x}" y="${y+15}" fill="${color(span.fg)}" font-weight="${span.attributes&1?700:400}" font-family="DejaVu Sans Mono,Cascadia Mono,Consolas,monospace" font-size="16" textLength="${Math.max(1,span.width*cw)}" lengthAdjust="spacingAndGlyphs">${escape(span.text)}</text>`;c+=span.width;}}
  const file=`${name}-${cols}`;await writeFile(join(out,file+'.txt'),frame);await writeFile(join(out,file+'.png'),new Resvg(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">${svg}</svg>`,{font:{loadSystemFonts:true}}).render().asPng());captures.push({file,cols,rows,method:'real native OpenTUI cell capture rasterized to PNG',data:'synthetic presentation only'});
 }finally{root.unmount();ui.renderer.destroy();store.close();}
}
await writeFile(join(out,'provenance.json'),JSON.stringify({sourceCommit:process.env.PERFECT_SOURCE_COMMIT??process.env.GITHUB_SHA??'unknown',platform:process.platform,node:process.version,captures},null,2));console.log(JSON.stringify(captures));
